### ISSUE TITLE
Implementing navbar functionality

### ISSUE THREAD

**Issue by jericahuang** [Thai-Construct/prj-rev-bwfs-tea-cozy#1]
https://github.com/Thai-Construct/prj-rev-bwfs-tea-cozy/blob/master/04_FINAL_tea_cozy/index.html#L14-L16

To implement the navbar functionality, you'll want to link these to an ID in the page so that when clicked, it'll jump to that section. For example

`<a href= "#Mission">Mission</a>`

And when you do that you'll want to set the corresponding ID to an HTML element. Bouncing off the former example,

```
<div id="Mission">
```

**Comment by Thai-Construct** [comment]
I missed this part. Thanks for pointing it out! I will apply the change on this.
