### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by jericahuang** [Thai-Construct/prj-rev-bwfs-tea-cozy#5]
Excellent job creating the Tea Cozy site! Your page resembles the specification closely and you clearly demonstrated mastery of styling using flexbox, markup, and designing a complex site while maintaining organization and clarity in your code. Check out the more specific comments I made on Github for improvement! The biggest area for improvement is implementing the navbar functionality and there are a few minor deviances from the spec. But overall this project met our expectations 👍 

I hope you enjoyed this project; it was a tough one and you have a lot to be proud of! You’re in a terrific position to succeed in this program and beyond and I encourage you to keep up the great work! For a further challenge, try embedding a Google Map into the page under Contact Us. I think it's a challenge you're ready for!

**Comment by Thai-Construct** [comment]
Thank you! Your words give me more motivation on this course. I'm trying my best to practice my skills over this course. When I have time I will come back to give more challenge on this project. Again, thanks!
